BTN_NIKKE = "assets/ui/btn_nikke.png"
QUIT_GAME_CONFIRM = "assets/ui/quit_game_confirm.png"

QUIT_CONFIRM_THRESHOLD = 0.88
QUIT_CONFIRM_MIN_SCALE = 0.55
QUIT_CONFIRM_MAX_SCALE = 1.35

MAX_ESC_WASH = 40
NAV_TEMPLATE_INTERVAL = 0.35
ESC_WASH_INTERVAL = 0.65
LOBBY_READY_INTERVAL = 0.35
LOBBY_READY_SETTLE = 0.35
WAREHOUSE_LOAD_INTERVAL = 0.55
WAREHOUSE_CLICK_SETTLE = 2.0
