"""搜索栏 / 筛选栏模板路径与匹配阈值。"""

BTN_SEARCH_EXECUTE = "assets/ui/btn_search_icon.png"
SEARCH_BOX_ACTIVE = "assets/ui/search_box_active.png"
BTN_FILTER = "assets/ui/btn_filter.png"
BTN_FILTER_CLEAR = "assets/ui/btn_filter_clear.png"

SEARCH_BOX_THRESHOLD = 0.70
SEARCH_BOX_MIN_SCALE = 0.55
SEARCH_BOX_MAX_SCALE = 1.35
SEARCH_BOX_MIN_WIDTH = 80

SEARCH_EXECUTE_THRESHOLD = 0.62
SEARCH_EXECUTE_MIN_SCALE = 0.55
SEARCH_EXECUTE_MAX_SCALE = 1.35

SEARCH_TOGGLE_THRESHOLD = 0.55
SEARCH_TOGGLE_MIN_SCALE = 0.55
SEARCH_TOGGLE_MAX_SCALE = 1.35
SEARCH_TOGGLE_MAX_TOOLBAR_X_RATIO = 0.36

FILTER_BTN_THRESHOLD = 0.78
FILTER_CLEAR_THRESHOLD = 0.58
FILTER_CLEAR_MIN_SCALE = 0.55
FILTER_CLEAR_MAX_SCALE = 1.35

WEAPON_FILTER_THRESHOLD = 0.78
WEAPON_FILTER_MIN_SCALE = 0.55
WEAPON_FILTER_MAX_SCALE = 1.35

SEARCH_INPUT_OFFSET_X = -80
SEARCH_CLEAR_OFFSET_X = 60

TEMPLATE_FIND_RETRIES = 8
TEMPLATE_FIND_INTERVAL = 0.8
